### ISSUE TITLE
Reliance on placehold.it

### ISSUE THREAD

**Issue by dschuermann** [jeremymouton/cointipper#6]
I have a feature request:
It would be great to have a version that does not rely on placehold.it for displaying the placeholders. A self-hosted version should not rely on external services in the best case.

**Comment by jeremymouton** [comment]
You're right, I should change it to use an SVG instead.

**Comment by jeremymouton** [comment]
You know what's better than SVG? Good ol' text.

I've updated the demo page as well: https://jeremymouton.github.io/cointipper/

**Comment by dschuermann** [comment]
Awesome, thanks for your fast help. Now https://www.openkeychain.org/ no longer links to external images (at least on most pages).

**Comment by jeremymouton** [comment]
This is great! Thanks for sharing.

I noticed some of the table border styles from your `main.css` are leaking into the Cointipper modal.
I should explicitly disable borders inside the modal tables by default. I think it would look better.
